baseURL = "https://networkingday.awsguru.top/"
ignoreFiles = [ "\\.files/README.md$",  ]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Networking Day Advanced on AWS workshop"
theme = "hugo-theme-learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
  hrefTargetBlank = true

[params]
  editURL = "https://github.com/sun-biao/secworkshop/edit/master/content/"
  themeVariant = "mine"
  showVisitedLinks = false
  author = "AWS Networking TFC<hxh@amazon.com>"
  description = "AWS Networking"
  disableSearch = false
  disableAssetsBusting = false
  disableShortcutsTitle = true
  branch = "master"
  pygmentsUseClasses = true
  pygmentsCodeFences = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle = "tango"
  codeRepoName = "hxhwing/NetworkingDay-Advanced"


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/hxhwing/NetworkingDay-Advanced"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "https://github.com/hxhwing/NetworkingDay-Advanced/issues"
weight = 40

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]